name: ponyc update breakage test

on:
  repository_dispatch:
    types: [shared-docker-linux-builders-updated]

jobs:
  vs-ponyc-master:
    name: Verify master against ponyc master
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test with against ponyc master
        run: make test
